Repository Coaktion/aktie-mui, pull requests merged in 2024-04, with the labels that each got.

#19 feat: adding limitTagsProps
  src/auto-complete-multiple.tsx
Labels: feature

#20 release:v/1.1.1
  package-lock.json
  package.json
Labels: skip-changelog

#22 feat: adding select option to multiple autocomplete
  __tests__/auto-complete-multiple.test.tsx
  package-lock.json
  package.json
  src/auto-complete-multiple.tsx
  src/auto-complete.tsx
Labels: feature

#23 release v.1.1.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#24 fix: adding margin to select all option
  src/auto-complete-multiple.tsx
Labels: bugfix

#25 release v.1.1.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#28 fix: fixed height auto complete multiple
  __tests__/auto-complete-multiple.test.tsx
  src/auto-complete-multiple.tsx
Labels: bugfix

#29 release v1.1.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#30 feat: add custom-loading-with-title component
  __tests__/custom-loading-with-title.test.tsx
  src/custom-loading-with-title.tsx
  src/index.ts
Labels: feature

#31 chore(release): v1.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog

#32 fix: changing chip size
  __tests__/auto-complete-multiple.test.tsx
  src/auto-complete-multiple.tsx
Labels: bugfix

#33 chore(release): v1.2.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: skip-changelog
